const P=['SENSE','UNDERSTAND','ASSESS','DECIDE','ACT','FEEDBACK'];
const STEP_CN=['感知環境','理解情境','評估風險','安全決策','執行動作','回饋小晴'];
const scenes=[
sc('plan','規劃行程','我要去市立醫院','DEPARTURE','公車站','建議搭乘 307 號公車，預計 2 分鐘後抵達。','LOW','PLAN','READY','NEUTRAL','busstop','ROUTE: 307','GPS + Transit','Destination parsed','LOW','SELECT 307'),
sc('wait','等待公車','307 號公車即將抵達','BUS STOP','公車站','307 號公車預計 2 分鐘後抵達。','LOW','MONITOR','READY','NEUTRAL','busstop','BUS ETA 2:00','Camera + Transit','Approaching vehicles','LOW','KEEP WAITING'),
sc('bus','辨識公車','這是正確的公車','BUS DETECTION','公車站','307 號公車已抵達，就在您的右前方。','LOW','MATCH','RIGHT','RIGHT','bus','BUS · 307','Camera + OCR','Route 307 matched','LOW','BOARD RIGHT'),
sc('boarding','上車引導','車門在右前方','BOARDING','307 公車站','車門在您的右前方，請跟著牽繩上車。','MED','GUIDE','RIGHT','RIGHT','bus','BUS DOOR','Depth 1.8m','Door is open','MED','MOVE RIGHT'),
sc('onbus','搭乘公車','距離目的地還有 2 站','TRANSIT','307 公車內','目前距離目的地還有 2 站。','LOW','TRACK','SOFT','NEUTRAL','onbus','2 STOPS','GPS + Route','Position tracked','LOW','MONITOR'),
sc('exit','準備下車','下一站是市立醫院','TRANSIT · ARRIVAL','307 公車內','下一站是市立醫院，請準備下車。','LOW','ALERT','DOUBLE','FORWARD','onbus','NEXT: HOSPITAL','GPS + Stop ID','Destination next','LOW','PREPARE EXIT'),
sc('street','街道導航','醫院入口還有 120 公尺','WALKING GUIDE','醫院周邊人行道','醫院入口距離約 120 公尺，我帶你過去。','LOW','FORWARD','SOFT','FORWARD','street','DIST 120m','Map + Camera','Walk route clear','LOW','MOVE FORWARD'),
sc('obstacle','發現障礙','違停車輛阻擋人行道','OBSTACLE','醫院周邊人行道','前方有人行道障礙，請稍候。','HIGH','ANALYZE','DANGER','STOP','obstacle','VEHICLE · 3.2m','Vehicle detected','Path blocked','HIGH','ASSESS ROUTE'),
sc('stop','Guardian 阻擋','Movement Blocked','GUARDIAN AI','醫院周邊人行道','目前路徑不安全，我已停止前進。','HIGH','REJECT','STOP','STOP','obstacle','COMMAND: FORWARD','Environment blocked','Collision risk high','HIGH','REJECT / STOP'),
sc('corridor','安全廊道','Safe Corridor Found','REPLANNING','醫院周邊人行道','請稍微往左，我會帶你繞過前方障礙。','LOW','LEFT','LEFT','LEFT','corridor','LEFT 1.4m','Compare L / R','Human clearance valid','LOW','MOVE LEFT'),
sc('red','紅燈等待','目前為紅燈','CROSSWALK','醫院前路口','目前為紅燈，請停下等待。','HIGH','STOP','STOP','STOP','red','SIGNAL: RED','Traffic light red','Crossing unsafe','HIGH','BLOCK'),
sc('green','安全穿越','綠燈，可以通行','CROSSWALK','醫院前路口','綠燈，車流已淨空，可以通行。','LOW','PASS','FORWARD','FORWARD','green','SIGNAL: GREEN','Signal + Vehicle','Crosswalk clear','LOW','PASS / MOVE'),
sc('hospital','進入醫院','切換室內導航','MODE SWITCH','市立醫院大廳','已進入市立醫院，我已切換至室內導航。','LOW','SWITCH','SOFT','FORWARD','hospital','GPS: WEAK','Indoor map found','Building recognized','LOW','INDOOR ON'),
sc('indoor','前往眼科','眼科在二樓','INDOOR ROUTE','市立醫院大廳','好的，眼科在二樓，我帶你過去。','LOW','ROUTE','RIGHT','RIGHT','hospital','TARGET: 2F','Intent + Indoor map','Ophthalmology 2F','LOW','ROUTE ELEVATOR'),
sc('elevator','找到電梯','電梯門在正前方','OBJECT GUIDANCE','一樓電梯廳','已抵達電梯，電梯門在您的正前方。','LOW','WAIT','STOP','STOP','elevator','ELEVATOR · 1.2m','Door detected','Safe waiting distance','LOW','WAIT'),
sc('room','抵達診間','205 眼科診間','OCR · SEMANTICS','二樓眼科','205 診間已抵達，候診區在您的右側。','LOW','ARRIVE','ARRIVED','STOP','room','OCR: 205','Text + Room sign','Ophthalmology matched','LOW','ARRIVED'),
sc('payment','前往繳費','重新規劃室內目的地','INDOOR REROUTE','二樓眼科','繳費櫃台在一樓，我們現在出發。','LOW','REROUTE','LEFT','LEFT','hospital','TARGET: PAYMENT','New user intent','Counter at 1F','LOW','NEW ROUTE'),
sc('home','安全抵達','Journey Completed','RETURN HOME','小晴家中','已安全回到家，家人已收到平安通知。','LOW','COMPLETE','ARRIVED','STOP','home','STATUS: HOME','Journey complete','All phases safe','LOW','NOTIFY FAMILY'),
sc('keys','尋找鑰匙','鑰匙在水杯旁邊','OBJECT SEARCH','小晴家中','鑰匙在桌子的右側，水杯旁邊。','LOW','FOUND','RIGHT','RIGHT','keys','KEYS · 91%','Room scan','Keys beside cup','LOW','POINT RIGHT'),
sc('companion','陪伴模式','我在，慢慢說就好','COMPANION','小晴家中','今天辛苦了。我在，慢慢說就好。','LOW','LISTEN','CALM','NEUTRAL','companion','LISTENING','Voice emotion','Xiaoqing is tired','LOW','RESPOND')];
function sc(id,rail,title,phase,loc,speech,risk,decision,haptic,leash,env,det,sense,understand,assess,act){return{id,rail,title,phase,loc,speech,risk,decision,haptic,leash,env,det,sense,understand,assess,act}}
function resolvedDecision(s){return s.risk==='HIGH'&&s.decision==='ANALYZE'?'BLOCK & REPLAN':s.decision}
function resolvedAction(s){return s.risk==='HIGH'&&s.act==='ASSESS ROUTE'?'STOP & REPLAN':s.act}
let index=0,sub=0,view='god',timer=null,directorOpen=false,navigationActive=true;const $=s=>document.querySelector(s);
function actorHuman(){return '<div class="human3d"><div class="h-head"><i class="hair"></i><i class="glasses"></i><i class="earbud"></i></div><div class="h-neck"></div><div class="h-body"><i class="strap"></i></div><div class="h-arm left"><i></i></div><div class="h-arm right"><i></i><b class="controller3d">•••</b></div><div class="h-leg left"><i></i></div><div class="h-leg right"><i></i></div><span class="actor-label">小晴</span></div>'}
function actorPupper(){return '<div class="pupper3d"><div class="p3-head"><i class="camera-lens"></i><i class="p3-eye one"></i><i class="p3-eye two"></i></div><div class="p3-body"><span>P3</span></div><div class="p3-leg front"><i class="joint"></i><b></b></div><div class="p3-leg front2"><i class="joint"></i><b></b></div><div class="p3-leg back"><i class="joint"></i><b></b></div><div class="p3-leg back2"><i class="joint"></i><b></b></div><span class="actor-label">Pupper v3</span></div>'}
function hazardWorld(s){const mode=s.id==='obstacle'?'detecting':s.id==='stop'?'blocked':'rerouting',title=s.id==='obstacle'?'VEHICLE DETECTED · 3.2m':s.id==='stop'?'MOVEMENT BLOCKED':'SAFE CORRIDOR · LEFT';return `<div class="hazard-world ${mode}"><div class="hazard-shade"></div><div class="van-risk"><span>VEHICLE</span><b>3.2m · HIGH</b></div><div class="pupper-lock"><span>PUPPER V3</span><b>GUIDE LINK ACTIVE</b></div><div class="hazard-footprint"></div>${mode==='rerouting'?'<div class="safe-route"><i></i><i></i><i></i><b>SAFE CORRIDOR</b></div>':''}${mode==='blocked'?'<div class="guardian-stop"><i>!</i><span>GUARDIAN AI<b>MOVEMENT BLOCKED</b></span></div>':''}<div class="hazard-readout"><small>${mode==='rerouting'?'HUMAN + ROBOT CLEARANCE':'UPPER + GROUND HAZARD CHECK'}</small><b>${title}</b></div></div>`}
function world(s){let inner='<div class="horizon"></div><div class="sidewalk"></div><div class="road"></div>',actors=actorHuman()+actorPupper()+'<div class="leash3d"></div>';
if(['obstacle','stop','corridor'].includes(s.id))return hazardWorld(s);
if(['plan','wait'].includes(s.id))inner+='<div class="bus" style="right:-12%;transform:scale(.65)"></div><div class="scene-caption">BUS STOP · 307 ETA 02:00</div>';
if(['bus','boarding'].includes(s.id))inner+='<div class="bus"></div><div class="scene-caption">307 BUS · ROUTE MATCH</div>';
if(['onbus','exit'].includes(s.id))return `<div class="god-view"><div class="building" style="top:7%;height:80%;background:#d5e2e3;border-color:#315d9f">307 公車車廂<small>CURRENT STOP · ${s.id==='exit'?'下一站 市立醫院':'民生社區'}</small></div>${actors}<div class="scene-caption">REMAINING · ${s.id==='exit'?'1':'2'} STOPS</div></div>`;
if(s.id==='street')inner+='<div class="route-path"></div><div class="scene-caption">WALKING GUIDE · 120m</div>';
if(['obstacle','stop'].includes(s.id))inner+='<div class="obstacle-car"></div><div class="danger-zone"></div><div class="scene-caption">VEHICLE BLOCKING PATH</div>';
if(s.id==='corridor')inner+='<div class="obstacle-car"></div><div class="danger-zone"></div><div class="safe-corridor"></div><div class="scene-caption">HUMAN + ROBOT SAFE CORRIDOR · LEFT</div>';
if(['red','green'].includes(s.id))inner+='<div class="crosswalk"></div><div class="traffic '+s.id+'"><i></i><i></i><i></i></div><div class="scene-caption">SIGNAL '+s.id.toUpperCase()+' · VEHICLE '+(s.id==='green'?'CLEAR':'CHECK')+'</div>';
if(['hospital','indoor','payment'].includes(s.id))return `<div class="god-view"><div class="building">＋ 市立醫院<small>${s.id==='hospital'?'INDOOR MAP AVAILABLE':s.id==='payment'?'NEW DESTINATION · PAYMENT 1F':'LOBBY → ELEVATOR → 2F EYE CLINIC'}</small></div><div class="route-path"></div>${actors}<div class="scene-caption">INDOOR NAVIGATION</div></div>`;
if(s.id==='elevator')return `<div class="god-view" style="background:#9aa8a5"><div class="elevator"></div>${actors}<div class="scene-caption">SAFE WAITING DISTANCE · 1.2m</div></div>`;
if(s.id==='room')return `<div class="god-view" style="background:#d5dfdc"><div class="room-sign">205<small>眼科 OPHTHALMOLOGY</small></div>${actors}<div class="scene-caption">OCR MATCH · ARRIVED</div></div>`;
if(['home','keys','companion'].includes(s.id)){let extras=s.id==='keys'?'<div class="detect-box" style="left:59%;top:39%;width:65px;height:62px"><span class="detect-tag">KEYS · 91%</span></div>':'';return `<div class="god-view"><div class="home-room"></div><div class="table"></div><div class="keys">⌘</div><div class="cup"></div>${actors}${extras}<div class="scene-caption">${s.id==='companion'?'COMPANION MODE · LISTENING':s.id==='home'?'SAFE ARRIVAL · HOME':'OBJECT SEARCH'}</div></div>`}
return `<div class="god-view">${inner}${actors}<div class="scene-caption">REALITY · GOD VIEW</div></div>`}
function user(s){let paused=!navigationActive,waiting=sub<4,arrow=paused||waiting?'●':s.leash==='LEFT'?'↖':s.leash==='RIGHT'?'↗':s.leash==='FORWARD'?'↑':s.leash==='STOP'?'●':'◎',danger=s.risk==='HIGH',active=sub===5&&!paused?(s.haptic==='LEFT'?'left':s.haptic==='RIGHT'?'right':'both'):'none',message=paused?'導航已暫停。再次按下導航鍵即可繼續。':sub===0?'Pupper 正在觀察前方環境。':sub===1?'AI 正在理解目前情境。':sub===2?'Guardian AI 正在評估風險。':sub===3?'安全決策已完成，準備執行。':sub===4?'Pupper 正在執行引導動作。':s.speech;return `<div class="user-view"><div class="user-center"><div class="ear-icon">◖</div><small>${sub===5?'HEARING · BLUETOOTH EARPHONE':'SYSTEM · PROCESSING'}</small><h2>「${message}」</h2><div class="direction-arrow ${danger||paused||waiting?'stop':''}">${arrow}</div><small>LEASH · ${paused?'PAUSED':sub<4?'WAITING':s.leash}</small><div class="haptic-viz"><span class="${active==='left'||active==='both'?'active':''} ${danger?'danger':''}">LEFT</span><span class="${active==='right'||active==='both'?'active':''} ${danger?'danger':''}">RIGHT</span></div></div><div class="controller-feedback" aria-live="polite"></div><div class="controller"><button class="nav ${navigationActive?'is-on':'is-paused'}" data-controller="navigation"><i>${navigationActive?'Ⅱ':'▶'}</i><b>${navigationActive?'暫停導航':'啟動導航'}</b><small>${navigationActive?'Navigation On':'Navigation Paused'}</small></button><button class="voice" data-controller="voice"><i>◉</i><b>語音互動</b><small>按住說話</small></button><button class="emergency" data-controller="sos"><i>!</i><b>緊急求助</b><small>長按 SOS</small></button></div></div>`}
function ai(s){const hazard=['obstacle','stop','corridor'].includes(s.id);return `<div class="ai-view"><div class="camera-feed ${s.risk==='HIGH'&&sub>=2?'danger-camera':''} ${hazard?'hazard-camera':''}"><div class="camera-object" data-label="${s.det}"></div><div class="reticle"></div><div class="cam-meta">PUPPER CAM 01 · DEPTH ACTIVE<br>TRACKING · STABLE<br>FRAME 0248 · MOCK</div></div><div class="ai-panel"><span>PUPPER V3 · AI BRAIN</span><div class="ai-metric ${sub===0?'step-active':''}"><small>SENSE</small><b>${s.sense}</b></div><div class="ai-metric ${sub===1?'step-active':''}"><small>UNDERSTAND</small><b>${s.understand}</b></div><div class="ai-metric ${s.risk==='HIGH'&&sub>=2?'danger-metric':''} ${sub===2?'step-active':''}"><small>RISK ASSESSMENT</small><b>${sub<2?'PENDING':s.assess}</b></div><div class="ai-decision ${s.risk==='HIGH'&&sub>=3?'danger':''} ${sub===3?'step-active':''}"><small>GUARDIAN DECISION</small><b>${sub<3?'PENDING':resolvedDecision(s)}</b></div><div class="ai-metric ${sub===4?'step-active':''}"><small>ACTION OUTPUT</small><b>${sub<4?'STANDBY':resolvedAction(s)}</b></div><div class="ai-metric ${sub===5?'step-active':''}"><small>USER FEEDBACK</small><b>${sub<5?'STANDBY':s.haptic+' + VOICE'}</b></div></div></div>`}
function stepDescription(s){return [s.sense,s.understand,'風險程度：'+s.assess,'Guardian AI：'+resolvedDecision(s),'動作輸出：'+resolvedAction(s),'語音「'+s.speech+'」'][sub]}
function decorate(content,s,type){return `<div class="stage-state sub-${sub} view-${type} ${s.risk==='HIGH'?'high-risk':''}">${content}<div class="process-card"><i>${sub+1}</i><div><b>${P[sub]} · ${STEP_CN[sub]}</b><span>${stepDescription(s)}</span></div></div></div>`}
function renderView(){const s=scenes[index],vp=$('#viewport');if(view==='god')vp.innerHTML=decorate(world(s),s,'god');else if(view==='user')vp.innerHTML=decorate(user(s),s,'user');else if(view==='ai')vp.innerHTML=decorate(ai(s),s,'ai');else vp.innerHTML=`<div class="compare-view"><div><span class="compare-label">小晴感受到的</span>${decorate(user(s),s,'user')}</div><div><span class="compare-label">Pupper 看見與決定的</span>${decorate(ai(s),s,'ai')}</div></div>`}
function render(){const s=scenes[index],riskReady=sub>=2,decisionReady=sub>=3,actionReady=sub>=4,feedbackReady=sub>=5,high=s.risk==='HIGH';$('#headerScene').textContent=String(index+1).padStart(2,'0')+' · '+s.rail;$('#sceneIndex').textContent=String(index+1).padStart(2,'0')+' / '+scenes.length;$('#scenePhase').textContent=s.phase+' · '+P[sub];$('#sceneTitle').textContent=s.title;$('#sceneSubtitle').textContent=subtext(s,sub);$('#locationText').textContent=s.loc;$('#speechText').textContent=feedbackReady?s.speech:'系統正在完成安全決策流程…';$('#riskText').textContent=riskReady?s.risk:'PENDING';$('#decisionText').textContent=decisionReady?resolvedDecision(s):'PENDING';$('#hapticText').textContent=feedbackReady?s.haptic:'STANDBY';$('#leashText').textContent=!navigationActive?'PAUSED':actionReady?s.leash:'STANDBY';$('#riskText').classList.toggle('danger-text',high&&riskReady);$('#decisionText').classList.toggle('danger-text',high&&decisionReady);$('#safetyLabel').classList.toggle('danger-text',high&&decisionReady);$('#safetyLabel').textContent=!decisionReady?'安全狀態：分析中':'安全狀態：'+(high?'阻擋中':s.risk==='MED'?'注意':'正常');$('#journeyProgress').style.width=((index+1)/scenes.length*100)+'%';$('#directorScene').textContent=String(index+1).padStart(2,'0')+' · '+s.rail;$('#substepText').textContent=`STEP ${sub+1} / 6 · ${P[sub]}`;document.querySelectorAll('.rail-scene').forEach((el,i)=>el.className='rail-scene '+(i<index?'done':i===index?'active':''));document.querySelectorAll('.pipe-step').forEach((el,i)=>el.className='pipe-step '+(i<sub?'done':i===sub?'active':''));$('#jumpSelect').value=index;renderView();if(s.id==='home'&&sub===5)$('#familyToast').classList.add('show');else $('#familyToast').classList.remove('show')}
function subtext(s,n){return [s.sense,s.understand,'風險評估：'+s.assess,'Guardian AI 決策：'+resolvedDecision(s),'Pupper 執行：'+resolvedAction(s),'小晴收到語音、震動與牽引回饋。'][n]}
function next(){if(sub<5)sub++;else if(index<scenes.length-1){index++;sub=0}else{pause()}render()}function prev(){if(sub>0)sub--;else if(index>0){index--;sub=5}render()}function pause(){clearInterval(timer);timer=null;$('#playBtn').textContent='▶ AUTO'}function play(){if(timer){pause();return}$('#playBtn').textContent='Ⅱ PAUSE';timer=setInterval(next,1800)}
function init(){const rail=$('#sceneRail'),sel=$('#jumpSelect');rail.innerHTML=scenes.map((s,i)=>`<div class="rail-scene" data-i="${i}">${String(i+1).padStart(2,'0')} · ${s.rail}</div>`).join('');sel.innerHTML=scenes.map((s,i)=>`<option value="${i}">${String(i+1).padStart(2,'0')} · ${s.rail}</option>`).join('');$('#pipeline').innerHTML=P.map((x,i)=>`<button class="pipe-step" data-sub="${i}" title="查看 ${STEP_CN[i]}"><i>${i+1}</i><span>${x}<small>${STEP_CN[i]}</small></span></button>`).join('');rail.addEventListener('click',e=>{const x=e.target.closest('.rail-scene');if(x){index=+x.dataset.i;sub=0;render()}});$('#pipeline').addEventListener('click',e=>{const step=e.target.closest('[data-sub]');if(step){pause();sub=+step.dataset.sub;render()}});render()}
function startJourney(){$('#splash').classList.remove('show-system');$('#splash').classList.add('hidden');$('#app').classList.remove('hidden');$('#directorToggle').classList.remove('hidden');init()}$('#homeBtn').onclick=()=>{pause();$('#app').classList.add('hidden');$('#director').classList.add('hidden');$('#directorToggle').classList.add('hidden');$('#splash').classList.remove('hidden');$('#splash').classList.remove('show-system')};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-view]').forEach(x=>x.classList.remove('active'));b.classList.add('active');view=b.dataset.view;renderView()});$('#nextBtn').onclick=next;$('#prevBtn').onclick=prev;$('#playBtn').onclick=play;$('#resetBtn').onclick=()=>{pause();index=0;sub=0;render()};$('#jumpSelect').onchange=e=>{index=+e.target.value;sub=0;render()};$('#directorToggle').onclick=()=>{directorOpen=!directorOpen;$('#director').classList.toggle('hidden',!directorOpen);$('#directorToggle').querySelector('b').textContent=directorOpen?'⌄':'⌃'};
const modal=$('#sosModal');$('#sosBtn').onclick=()=>modal.classList.remove('hidden');$('#closeSos').onclick=$('#cancelSos').onclick=()=>modal.classList.add('hidden');$('#confirmSos').onclick=()=>{modal.classList.add('hidden');$('#familyToast').innerHTML='<span>GPT GUARDIAN · EMERGENCY</span><b>位置已分享給緊急聯絡人</b><small>未自動聯絡警察或醫療單位</small>';$('#familyToast').classList.add('show')};document.addEventListener('keydown',e=>{if($('#app').classList.contains('hidden'))return;if(e.key==='ArrowRight'||e.key===' ')next();if(e.key==='ArrowLeft')prev();if(e.key.toLowerCase()==='p')play();if(e.key.toLowerCase()==='d')$('#directorToggle').click();if(e.key.toLowerCase()==='1')document.querySelector('[data-view="god"]').click();if(e.key.toLowerCase()==='2')document.querySelector('[data-view="user"]').click();if(e.key.toLowerCase()==='3')document.querySelector('[data-view="ai"]').click();if(e.key.toLowerCase()==='4')document.querySelector('[data-view="compare"]').click()});
$('#viewport').addEventListener('click',e=>{const button=e.target.closest('[data-controller]');if(!button)return;const action=button.dataset.controller,viewBox=button.closest('.user-view'),feedback=viewBox.querySelector('.controller-feedback');button.classList.add('pressed');setTimeout(()=>button.classList.remove('pressed'),450);if(action==='sos'){modal.classList.remove('hidden');return}if(action==='navigation'){navigationActive=!navigationActive;if(!navigationActive)pause();render();const currentFeedback=$('#viewport').querySelector('.controller-feedback');if(currentFeedback){currentFeedback.textContent=navigationActive?'▶ NAVIGATION STARTED · 導航已啟動':'Ⅱ NAVIGATION PAUSED · 導航已暫停';currentFeedback.classList.add('show');setTimeout(()=>currentFeedback.classList.remove('show'),2200)}return}feedback.textContent='● LISTENING · 請說出您的需求';feedback.classList.add('show');setTimeout(()=>feedback.classList.remove('show'),2200)});
const featureModal=$('#featureModal');document.querySelectorAll('[data-feature-map]').forEach(button=>button.addEventListener('click',()=>{featureModal.classList.remove('hidden');document.body.style.overflow='hidden';$('#closeFeatureMap').focus()}));function closeFeatureMap(){featureModal.classList.add('hidden');document.body.style.overflow=''}$('#closeFeatureMap').onclick=closeFeatureMap;featureModal.addEventListener('click',e=>{if(e.target===featureModal)closeFeatureMap()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!featureModal.classList.contains('hidden'))closeFeatureMap()});
const splash=$('#splash');document.querySelectorAll('[data-open-system]').forEach(button=>button.addEventListener('click',()=>splash.classList.add('show-system')));$('#backLanding').onclick=()=>splash.classList.remove('show-system');document.addEventListener('keydown',e=>{if(e.key==='Escape'&&splash.classList.contains('show-system')&&featureModal.classList.contains('hidden'))splash.classList.remove('show-system')});
